/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class engine_BackendBridge */

#ifndef _Included_engine_BackendBridge
#define _Included_engine_BackendBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     engine_BackendBridge
 * Method:    applyMove
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_engine_BackendBridge_applyMove
  (JNIEnv *, jclass, jstring);

/*
 * Class:     engine_BackendBridge
 * Method:    getBoardState
 * Signature: ()[[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_engine_BackendBridge_getBoardState
  (JNIEnv *, jclass);

/*
 * Class:     engine_BackendBridge
 * Method:    loadFEN
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_engine_BackendBridge_loadFEN
  (JNIEnv *, jclass, jstring);

/*
 * Class:     engine_BackendBridge
 * Method:    isCheckmate
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_engine_BackendBridge_isCheckmate
  (JNIEnv *, jclass);

/*
 * Class:     engine_BackendBridge
 * Method:    getLegalMoves
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_engine_BackendBridge_getLegalMoves
  (JNIEnv *, jclass);

/*
 * Class:     engine_BackendBridge
 * Method:    getSuggestedMove
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_engine_BackendBridge_getSuggestedMove
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
